* Open Editions

The Open Editions project publishes richly annotated open source literary texts. We aim to aggregate the literary knowledge that surrounds a text, codify that knowledge, and integrate it into the text. [[https://github.com/open-editions/article-jjq/blob/master/open-editions-online.pdf][Read our draft article for /James Joyce Quarterly/ where we discuss the project and its preliminary goals.]]

This is the master repository for the Open Editions website, [[http://open-editions.org][Open-Editions.org]]. The issues here represent meta-todo items for all texts.

For technical documentation, including the specification for an Open Edition, please see http://open-editions.org/docs

** Text Feature Status

The issues pages of the text repositories (see the list at http://github.com/open-editions) are the best place to see the most recently updated status of each text and text feature. But here's a table, for convenience:

| Text                    | Ulysses    | Portrait of the Artist | Dubliners | Finnegans Wake | Middlemarch |
|-------------------------+------------+------------------------+-----------+----------------+-------------|
| Author                  | Joyce      | Joyce                  | Joyce     | Joyce          | Eliot       |
| Line Nos.               | DONE       | DONE                   | DONE      | DONE           | TODO        |
| Dialogue Attribution    | DONE       | INPROGRESS             | DONE      | TODO           | DONE        |
| Place Names             | DONE       | DONE                   | DONE      | TODO           | TODO        |
| Geotagging              | TODO       | DONE                   | DONE      | TODO           | TODO        |
| Distinctive Words       | INPROGRESS | INPROGRESS             | TODO      | WONTFIX?       | TODO        |
| Cross-References        | INPROGRESS | INPROGRESS             | TODO      | TODO           | TODO        |
| Languages               | DONE       | DONE                   | TODO      | WONTFIX?       | TODO        |
| Free Indirect Discourse | TODO       | TODO                   | TODO      | TODO           | DONE        |
| Criticism Mapping       | TODO       | TODO                   | TODO      | INPROGRESS     | TODO        |
| Zenodo Archive          | DONE       | DONE                   | TODO      | TODO           | TODO        |

** Website: technical details. 

This website, [[http://open-editions.org]], is built from markdown, using Rib, Shake, and other Haskell tools. To build it, make sure you have Nix installed, and then run: 

#+BEGIN_SRC shell
nix-shell --run 'ghcid -T ":main generate"' 
#+END_SRC

Or to build it and watch the directory for changes, just remove ~generate~. 

Most of the layout is in Main.hs. Edition metadata is in Editions.hs, for now. 
