name: "CI"
on:
  pull_request:
  push:
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1
      - name: Install Nix
        uses: cachix/install-nix-action@v6
      - name: Install Rib and Build
        uses: cachix/cachix-action@v3  # This also runs nix-build.
        with:
          name: srid
      - name: Build Site
        run: nix-shell --run "cabal run"
      - name: Deploy to GH Pages 🚀
        uses: JamesIves/github-pages-deploy-action@3.5.9
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: dest # The folder the action should deploy.
