name: Nix CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: cachix/install-nix-action@v6
    - uses: cachix/cachix-action@v3  # This also runs nix-build.
      with:
        name: srid
    - name: Build
      run: nix-build
